### ISSUE TITLE
Googlewifi not working since HA 2022.6.7

### ISSUE THREAD

**Issue by TwitchingAstronaut** [djtimca/hagooglewifi#76] opened 2022-07-04 12:47 UTC
Hey,

my google WIFI integration hasn't been working since updating HA to 2022.6.7

I have tried Restarting HA, both with Google WIFI enabled and disabled.

I have just redownloaded the Google WIFI and deleted the integration and re-added it with no luck.

does anyone have any ideas

HomeAssistant Docker 2022.6.7 on Rpi4

![image](https://user-images.githubusercontent.com/91707474/177307616-dc7b9d03-4704-4e1e-bc89-4934e68645d1.png)

```
2022-07-05 20:49:27 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2022-07-05 20:49:47 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2022-07-05 20:50:21 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2022-07-05 20:50:40 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2022-07-05 20:51:24 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
```

**Comment by djtimca** [comment] 2022-07-05 16:05
I'm on 2022.6.7 and working fine, but not on RPI.

From the error it looks like it can't connect to the Google endpoint which would point to a network issue (or something on your network blocking that access). Doesn't appear to be an issue with the integration unless someone else can reproduce.

Closing for now - will wait for anyone else to confirm, otherwise assuming it is local to your system.

**Closed by djtimca** 2022-07-05 16:05 UTC

**Comment by TwitchingAstronaut** [comment] 2022-07-06 12:25
looks like it was an "internal" issue
I reset my phone around the same time that 2022.6.7 dropped.
I had to reset the 2FA on my google account and it look like it broke the auth

**Comment by droopanu** [comment] 2023-03-14 04:08
Interesting, I had the same issue.
After about 6 months of trying to get it to work, I decided to generate the refresh token using another account connected to the same google home, and it finally worked ....
